import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import AuthRecoveryRedirect from "@/app/components/AuthRecoveryRedirect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthRecoveryRedirect />

        {/* NAV (desktop sidebar + mobile burger) */}
        <Nav />

        <div className="app-shell">
          <main className="app-content">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
