'use client'

import { useState } from 'react'
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Nav from "./components/Nav"
import AuthRecoveryRedirect from "@/app/components/AuthRecoveryRedirect"
import AuthModal from "./components/AuthModal"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
}

export default function RootLayout({ children }) {
  const [authOpen, setAuthOpen] = useState(false)
  const [authMode, setAuthMode] = useState('login')

  return (
    <html lang="da">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthRecoveryRedirect />

        <Nav
          openAuth={(mode) => {
            setAuthMode(mode)
            setAuthOpen(true)
          }}
        />

        <AuthModal
          open={authOpen}
          mode={authMode}
          onClose={() => setAuthOpen(false)}
        />

        <div className="app-shell">
          <main className="app-content">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
